const { v4: uuidv4 } = require("uuid");
const bcrypt = require("bcryptjs");

// Generate consistent UUIDs for relationships
const userIds = {
  john: uuidv4(),
  jane: uuidv4(),
  admin: uuidv4(),
};

const categoryIds = {
  burgers: uuidv4(),
  pizza: uuidv4(),
  beverages: uuidv4(),
  indian: uuidv4(),
};

const brandIds = {
  mcdonalds: uuidv4(),
  pizzahut: uuidv4(),
  dominos: uuidv4(),
};

const outletIds = {
  mcdonalds_cp: uuidv4(),
  mcdonalds_ln: uuidv4(),
  mcdonalds_rohini: uuidv4(),
  pizzahut_cp: uuidv4(),
  pizzahut_ln: uuidv4(),
  pizzahut_dwarka: uuidv4(),
  dominos_kb: uuidv4(),
  dominos_saket: uuidv4(),
  dominos_gurgaon: uuidv4(),
};

const menuItemIds = {
  // McDonald's items
  mcdonalds_bigmac: uuidv4(),
  mcdonalds_mcchicken: uuidv4(),
  mcdonalds_quarterpounder: uuidv4(),
  mcdonalds_mcveggie: uuidv4(),
  mcdonalds_coke: uuidv4(),
  mcdonalds_fries: uuidv4(),

  // Pizza Hut items
  pizzahut_margherita: uuidv4(),
  pizzahut_pepperoni: uuidv4(),
  pizzahut_veggie: uuidv4(),
  pizzahut_garlicbread: uuidv4(),
  pizzahut_pepsi: uuidv4(),

  // Domino's items
  dominos_margherita: uuidv4(),
  dominos_chicken: uuidv4(),
  dominos_veg: uuidv4(),
  dominos_garlicbread: uuidv4(),
  dominos_lemonade: uuidv4(),
  dominos_sprite: uuidv4(),
};

const seedData = {
  users: [
    {
      id: userIds.john,
      name: "John Doe",
      email: "john@example.com",
      phone: "+91-9876543210",
      password: bcrypt.hashSync("password123", 10),
      role: "customer",
      is_verified: true,
      is_active: true,
      email_verified_at: new Date(),
      preferences: {},
      notification_settings: { email: true, sms: false, push: true },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: userIds.jane,
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "+91-9876543211",
      password: bcrypt.hashSync("password123", 10),
      role: "customer",
      is_verified: true,
      is_active: true,
      email_verified_at: new Date(),
      preferences: {},
      notification_settings: { email: true, sms: false, push: true },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: userIds.admin,
      name: "Admin User",
      email: "admin@globaleats.com",
      phone: "+91-9876543212",
      password: bcrypt.hashSync("admin123", 10),
      role: "admin",
      is_verified: true,
      is_active: true,
      email_verified_at: new Date(),
      preferences: {},
      notification_settings: { email: true, sms: true, push: true },
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],

  categories: [
    {
      id: categoryIds.burgers,
      name: "Burgers",
      description: "Juicy burgers with various toppings",
      image_url:
        "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg",
      is_active: true,
      sort_order: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: categoryIds.pizza,
      name: "Pizza",
      description: "Fresh pizzas with authentic flavors",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      is_active: true,
      sort_order: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: categoryIds.beverages,
      name: "Beverages",
      description: "Refreshing drinks and beverages",
      image_url:
        "https://images.pexels.com/photos/434295/pexels-photo-434295.jpeg",
      is_active: true,
      sort_order: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: categoryIds.indian,
      name: "Indian",
      description: "Authentic Indian cuisine",
      image_url:
        "https://images.pexels.com/photos/1603901/pexels-photo-1603901.jpeg",
      is_active: true,
      sort_order: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],

  brands: [
    {
      id: brandIds.mcdonalds,
      name: "McDonald's",
      slug: "mcdonalds",
      description: "World famous burgers and fries",
      logo_url:
        "https://images.pexels.com/photos/4393021/pexels-photo-4393021.jpeg?auto=compress&cs=tinysrgb&w=200",
      banner_url:
        "https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg?auto=compress&cs=tinysrgb&w=800",
      cuisine_type: "Fast Food",
      average_rating: 4.2,
      total_reviews: 1250,
      is_active: true,
      is_featured: true,
      minimum_order_amount: 99,
      delivery_fee: 49,
      estimated_delivery_time: 25,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: brandIds.pizzahut,
      name: "Pizza Hut",
      slug: "pizza-hut",
      description: "Fresh pizzas with authentic taste",
      logo_url:
        "https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=200",
      banner_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=800",
      cuisine_type: "Pizza",
      average_rating: 4.0,
      total_reviews: 890,
      is_active: true,
      is_featured: true,
      minimum_order_amount: 199,
      delivery_fee: 39,
      estimated_delivery_time: 30,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: brandIds.dominos,
      name: "Domino's",
      slug: "dominos",
      description: "Hot pizzas delivered in 30 minutes",
      logo_url:
        "https://images.pexels.com/photos/4394612/pexels-photo-4394612.jpeg?auto=compress&cs=tinysrgb&w=200",
      banner_url:
        "https://images.pexels.com/photos/2619970/pexels-photo-2619970.jpeg?auto=compress&cs=tinysrgb&w=800",
      cuisine_type: "Pizza",
      average_rating: 4.1,
      total_reviews: 756,
      is_active: true,
      is_featured: false,
      minimum_order_amount: 149,
      delivery_fee: 29,
      estimated_delivery_time: 25,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],

  outlets: [
    {
      id: outletIds.mcdonalds_cp,
      brand_id: brandIds.mcdonalds,
      name: "McDonald's - Connaught Place",
      address: "Shop No. 12, Connaught Place, New Delhi",
      city: "New Delhi",
      state: "Delhi",
      postal_code: "110001",
      country: "India",
      latitude: 28.6315,
      longitude: 77.2167,
      phone: "+91-11-23456789",
      email: "cp@mcdonalds.in",
      is_active: true,
      is_delivery_available: true,
      is_pickup_available: true,
      delivery_radius: 8.0,
      operating_hours: {
        monday: { open: "09:00", close: "23:00", is_open: true },
        tuesday: { open: "09:00", close: "23:00", is_open: true },
        wednesday: { open: "09:00", close: "23:00", is_open: true },
        thursday: { open: "09:00", close: "23:00", is_open: true },
        friday: { open: "09:00", close: "24:00", is_open: true },
        saturday: { open: "09:00", close: "24:00", is_open: true },
        sunday: { open: "10:00", close: "23:00", is_open: true },
      },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: outletIds.mcdonalds_gurgaon,
      brand_id: brandIds.mcdonalds,
      name: "McDonald's - DLF Cyber City",
      address: "Building 5, DLF Cyber City, Gurgaon",
      city: "Gurgaon",
      state: "Haryana",
      postal_code: "122002",
      country: "India",
      latitude: 28.4947,
      longitude: 77.0856,
      phone: "+91-124-4567890",
      email: "dlf@mcdonalds.in",
      is_active: true,
      is_delivery_available: true,
      is_pickup_available: true,
      delivery_radius: 10.0,
      operating_hours: {
        monday: { open: "08:00", close: "23:00", is_open: true },
        tuesday: { open: "08:00", close: "23:00", is_open: true },
        wednesday: { open: "08:00", close: "23:00", is_open: true },
        thursday: { open: "08:00", close: "23:00", is_open: true },
        friday: { open: "08:00", close: "24:00", is_open: true },
        saturday: { open: "08:00", close: "24:00", is_open: true },
        sunday: { open: "09:00", close: "23:00", is_open: true },
      },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: outletIds.mcdonalds_noida,
      brand_id: brandIds.mcdonalds,
      name: "McDonald's - Sector 18 Noida",
      address: "Shop 101, Atta Market, Sector 18, Noida",
      city: "Noida",
      state: "Uttar Pradesh",
      postal_code: "201301",
      country: "India",
      latitude: 28.5685,
      longitude: 77.3272,
      phone: "+91-120-4567891",
      email: "noida@mcdonalds.in",
      is_active: true,
      is_delivery_available: true,
      is_pickup_available: true,
      delivery_radius: 6.0,
      operating_hours: {
        monday: { open: "09:00", close: "22:30", is_open: true },
        tuesday: { open: "09:00", close: "22:30", is_open: true },
        wednesday: { open: "09:00", close: "22:30", is_open: true },
        thursday: { open: "09:00", close: "22:30", is_open: true },
        friday: { open: "09:00", close: "23:30", is_open: true },
        saturday: { open: "09:00", close: "23:30", is_open: true },
        sunday: { open: "10:00", close: "22:30", is_open: true },
      },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: outletIds.pizzahut_khan,
      brand_id: brandIds.pizzahut,
      name: "Pizza Hut - Khan Market",
      address: "Shop No. 45, Khan Market, New Delhi",
      city: "New Delhi",
      state: "Delhi",
      postal_code: "110003",
      country: "India",
      latitude: 28.5984,
      longitude: 77.2301,
      phone: "+91-11-23456790",
      email: "khanmarket@pizzahut.in",
      is_active: true,
      is_delivery_available: true,
      is_pickup_available: true,
      delivery_radius: 7.0,
      operating_hours: {
        monday: { open: "11:00", close: "23:00", is_open: true },
        tuesday: { open: "11:00", close: "23:00", is_open: true },
        wednesday: { open: "11:00", close: "23:00", is_open: true },
        thursday: { open: "11:00", close: "23:00", is_open: true },
        friday: { open: "11:00", close: "24:00", is_open: true },
        saturday: { open: "11:00", close: "24:00", is_open: true },
        sunday: { open: "11:00", close: "23:00", is_open: true },
      },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: outletIds.pizzahut_dlf,
      brand_id: brandIds.pizzahut,
      name: "Pizza Hut - DLF Mall",
      address: "Food Court, DLF Mall of India, Noida",
      city: "Noida",
      state: "Uttar Pradesh",
      postal_code: "201301",
      country: "India",
      latitude: 28.5706,
      longitude: 77.3272,
      phone: "+91-120-4567892",
      email: "dlf@pizzahut.in",
      is_active: true,
      is_delivery_available: true,
      is_pickup_available: true,
      delivery_radius: 8.0,
      operating_hours: {
        monday: { open: "11:00", close: "23:00", is_open: true },
        tuesday: { open: "11:00", close: "23:00", is_open: true },
        wednesday: { open: "11:00", close: "23:00", is_open: true },
        thursday: { open: "11:00", close: "23:00", is_open: true },
        friday: { open: "11:00", close: "24:00", is_open: true },
        saturday: { open: "11:00", close: "24:00", is_open: true },
        sunday: { open: "11:00", close: "23:00", is_open: true },
      },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: outletIds.dominos_rohini,
      brand_id: brandIds.dominos,
      name: "Domino's - Rohini Sector 7",
      address: "Shop 15, Unity One Mall, Rohini Sector 7",
      city: "New Delhi",
      state: "Delhi",
      postal_code: "110085",
      country: "India",
      latitude: 28.7041,
      longitude: 77.1025,
      phone: "+91-11-4567893",
      email: "rohini@dominos.in",
      is_active: true,
      is_delivery_available: true,
      is_pickup_available: true,
      delivery_radius: 5.0,
      operating_hours: {
        monday: { open: "11:00", close: "23:00", is_open: true },
        tuesday: { open: "11:00", close: "23:00", is_open: true },
        wednesday: { open: "11:00", close: "23:00", is_open: true },
        thursday: { open: "11:00", close: "23:00", is_open: true },
        friday: { open: "11:00", close: "24:00", is_open: true },
        saturday: { open: "11:00", close: "24:00", is_open: true },
        sunday: { open: "11:00", close: "23:00", is_open: true },
      },
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: outletIds.dominos_saket,
      brand_id: brandIds.dominos,
      name: "Domino's - Saket Select City",
      address: "A-3, Select City Walk, Saket",
      city: "New Delhi",
      state: "Delhi",
      postal_code: "110017",
      country: "India",
      latitude: 28.5244,
      longitude: 77.2066,
      phone: "+91-11-4567894",
      email: "saket@dominos.in",
      is_active: true,
      is_delivery_available: true,
      is_pickup_available: true,
      delivery_radius: 7.0,
      operating_hours: {
        monday: { open: "10:30", close: "23:30", is_open: true },
        tuesday: { open: "10:30", close: "23:30", is_open: true },
        wednesday: { open: "10:30", close: "23:30", is_open: true },
        thursday: { open: "10:30", close: "23:30", is_open: true },
        friday: { open: "10:30", close: "24:00", is_open: true },
        saturday: { open: "10:30", close: "24:00", is_open: true },
        sunday: { open: "10:30", close: "23:30", is_open: true },
      },
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],

  menuItems: [
    // McDonald's items
    {
      id: menuItemIds.mcdonalds_bigmac,
      brand_id: brandIds.mcdonalds,
      category_id: categoryIds.burgers,
      name: "Big Mac",
      description:
        "Two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun",
      image_url:
        "https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg",
      base_price: 299.0,
      is_vegetarian: false,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 0,
      calories: 563,
      preparation_time: 10,
      is_available: true,
      sort_order: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: menuItemIds.mcdonalds_mcchicken,
      brand_id: brandIds.mcdonalds,
      category_id: categoryIds.burgers,
      name: "McChicken Deluxe",
      description: "Crispy chicken patty with fresh lettuce and mayo",
      image_url:
        "https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg",
      base_price: 199.0,
      is_vegetarian: false,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 1,
      calories: 420,
      preparation_time: 8,
      is_available: true,
      sort_order: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: menuItemIds.mcdonalds_quarterpounder,
      brand_id: brandIds.mcdonalds,
      category_id: categoryIds.burgers,
      name: "Quarter Pounder",
      description:
        "Quarter pound of fresh beef with cheese, lettuce, tomato, pickles, onions",
      image_url:
        "https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg",
      base_price: 349.0,
      is_vegetarian: false,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 0,
      calories: 520,
      preparation_time: 12,
      is_available: true,
      sort_order: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: menuItemIds.mcdonalds_mcveggie,
      brand_id: brandIds.mcdonalds,
      category_id: categoryIds.burgers,
      name: "McVeggie Deluxe",
      description: "Delicious vegetarian patty with fresh vegetables",
      image_url:
        "https://images.pexels.com/photos/580612/pexels-photo-580612.jpeg",
      base_price: 179.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 1,
      calories: 380,
      preparation_time: 8,
      is_available: true,
      sort_order: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: menuItemIds.mcdonalds_coke,
      brand_id: brandIds.mcdonalds,
      category_id: categoryIds.beverages,
      name: "Coca Cola",
      description: "Refreshing cold drink",
      image_url:
        "https://images.pexels.com/photos/434295/pexels-photo-434295.jpeg",
      base_price: 89.0,
      is_vegetarian: true,
      is_vegan: true,
      is_gluten_free: true,
      spice_level: 0,
      calories: 140,
      preparation_time: 2,
      is_available: true,
      sort_order: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: menuItemIds.mcdonalds_fries,
      brand_id: brandIds.mcdonalds,
      category_id: categoryIds.beverages,
      name: "McCafé Coffee",
      description: "Premium coffee blend",
      image_url:
        "https://images.pexels.com/photos/434295/pexels-photo-434295.jpeg",
      base_price: 129.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: true,
      spice_level: 0,
      calories: 15,
      preparation_time: 3,
      is_available: true,
      sort_order: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.mcdonalds,
      category_id: categoryIds.beverages,
      name: "McShake Vanilla",
      description: "Creamy vanilla milkshake",
      image_url:
        "https://images.pexels.com/photos/434295/pexels-photo-434295.jpeg",
      base_price: 159.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 0,
      calories: 420,
      preparation_time: 4,
      is_available: true,
      sort_order: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    // Pizza Hut items
    {
      id: uuidv4(),
      brand_id: brandIds.pizzahut,
      category_id: categoryIds.pizza,
      name: "Margherita Pizza",
      description: "Fresh tomatoes, mozzarella cheese, and basil",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 399.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 0,
      calories: 250,
      preparation_time: 15,
      is_available: true,
      sort_order: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.pizzahut,
      category_id: categoryIds.pizza,
      name: "Pepperoni Pizza",
      description: "Classic pepperoni with mozzarella cheese",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 499.0,
      is_vegetarian: false,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 1,
      calories: 320,
      preparation_time: 15,
      is_available: true,
      sort_order: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.pizzahut,
      category_id: categoryIds.pizza,
      name: "Chicken Supreme",
      description: "Chicken chunks, bell peppers, onions, and mushrooms",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 549.0,
      is_vegetarian: false,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 2,
      calories: 380,
      preparation_time: 18,
      is_available: true,
      sort_order: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.pizzahut,
      category_id: categoryIds.pizza,
      name: "Veggie Paradise",
      description: "Fresh vegetables with corn, capsicum, onions, and tomatoes",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 449.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 1,
      calories: 290,
      preparation_time: 16,
      is_available: true,
      sort_order: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.pizzahut,
      category_id: categoryIds.pizza,
      name: "BBQ Chicken",
      description: "Smoky BBQ chicken with onions and bell peppers",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 599.0,
      is_vegetarian: false,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 2,
      calories: 410,
      preparation_time: 20,
      is_available: true,
      sort_order: 5,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.pizzahut,
      category_id: categoryIds.beverages,
      name: "Pepsi",
      description: "Chilled Pepsi cola",
      image_url:
        "https://images.pexels.com/photos/434295/pexels-photo-434295.jpeg",
      base_price: 79.0,
      is_vegetarian: true,
      is_vegan: true,
      is_gluten_free: true,
      spice_level: 0,
      calories: 150,
      preparation_time: 2,
      is_available: true,
      sort_order: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    // Domino's items
    {
      id: uuidv4(),
      brand_id: brandIds.dominos,
      category_id: categoryIds.pizza,
      name: "Farmhouse Pizza",
      description:
        "Delightful combination of onion, capsicum, tomato & grilled mushroom",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 479.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 1,
      calories: 320,
      preparation_time: 15,
      is_available: true,
      sort_order: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.dominos,
      category_id: categoryIds.pizza,
      name: "Chicken Dominator",
      description:
        "Loaded with grilled chicken tikka, chicken keema, and chicken sausage",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 649.0,
      is_vegetarian: false,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 3,
      calories: 450,
      preparation_time: 18,
      is_available: true,
      sort_order: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.dominos,
      category_id: categoryIds.pizza,
      name: "Paneer Makhani",
      description: "Paneer & capsicum on makhani sauce with extra cheese",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 529.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 2,
      calories: 380,
      preparation_time: 16,
      is_available: true,
      sort_order: 3,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.dominos,
      category_id: categoryIds.pizza,
      name: "Mexican Green Wave",
      description:
        "Mexican herbs sprinkled on onion, capsicum, tomato & jalapeno",
      image_url:
        "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
      base_price: 459.0,
      is_vegetarian: true,
      is_vegan: false,
      is_gluten_free: false,
      spice_level: 2,
      calories: 310,
      preparation_time: 14,
      is_available: true,
      sort_order: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.dominos,
      category_id: categoryIds.beverages,
      name: "Domino's Lemonade",
      description: "Fresh lemon drink",
      image_url:
        "https://images.pexels.com/photos/434295/pexels-photo-434295.jpeg",
      base_price: 99.0,
      is_vegetarian: true,
      is_vegan: true,
      is_gluten_free: true,
      spice_level: 0,
      calories: 80,
      preparation_time: 3,
      is_available: true,
      sort_order: 1,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: uuidv4(),
      brand_id: brandIds.dominos,
      category_id: categoryIds.beverages,
      name: "Sprite",
      description: "Lemon lime flavored soft drink",
      image_url:
        "https://images.pexels.com/photos/434295/pexels-photo-434295.jpeg",
      base_price: 85.0,
      is_vegetarian: true,
      is_vegan: true,
      is_gluten_free: true,
      spice_level: 0,
      calories: 145,
      preparation_time: 2,
      is_available: true,
      sort_order: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],

  // Outlet Menu Items - Connect menu items to specific outlets
  outletMenuItems: [
    // McDonald's Connaught Place - All McDonald's items available
    {
      outlet_id: outletIds.mcdonalds_cp,
      menu_item_id: menuItemIds.mcdonalds_bigmac,
      outlet_price: 299.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_cp,
      menu_item_id: menuItemIds.mcdonalds_mcchicken,
      outlet_price: 199.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_cp,
      menu_item_id: menuItemIds.mcdonalds_quarterpounder,
      outlet_price: 349.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_cp,
      menu_item_id: menuItemIds.mcdonalds_mcveggie,
      outlet_price: 179.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_cp,
      menu_item_id: menuItemIds.mcdonalds_coke,
      outlet_price: 89.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_cp,
      menu_item_id: menuItemIds.mcdonalds_fries,
      outlet_price: 119.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // McDonald's Lajpat Nagar - Limited items
    {
      outlet_id: outletIds.mcdonalds_ln,
      menu_item_id: menuItemIds.mcdonalds_bigmac,
      outlet_price: 299.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_ln,
      menu_item_id: menuItemIds.mcdonalds_mcchicken,
      outlet_price: 199.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_ln,
      menu_item_id: menuItemIds.mcdonalds_mcveggie,
      outlet_price: 179.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_ln,
      menu_item_id: menuItemIds.mcdonalds_coke,
      outlet_price: 89.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_ln,
      menu_item_id: menuItemIds.mcdonalds_fries,
      outlet_price: 119.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // McDonald's Rohini - Budget pricing
    {
      outlet_id: outletIds.mcdonalds_rohini,
      menu_item_id: menuItemIds.mcdonalds_bigmac,
      outlet_price: 289.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_rohini,
      menu_item_id: menuItemIds.mcdonalds_mcchicken,
      outlet_price: 189.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_rohini,
      menu_item_id: menuItemIds.mcdonalds_mcveggie,
      outlet_price: 169.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.mcdonalds_rohini,
      menu_item_id: menuItemIds.mcdonalds_fries,
      outlet_price: 109.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // Pizza Hut Connaught Place - All Pizza Hut items
    {
      outlet_id: outletIds.pizzahut_cp,
      menu_item_id: menuItemIds.pizzahut_margherita,
      outlet_price: 399.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_cp,
      menu_item_id: menuItemIds.pizzahut_pepperoni,
      outlet_price: 499.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_cp,
      menu_item_id: menuItemIds.pizzahut_veggie,
      outlet_price: 449.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_cp,
      menu_item_id: menuItemIds.pizzahut_garlicbread,
      outlet_price: 199.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_cp,
      menu_item_id: menuItemIds.pizzahut_pepsi,
      outlet_price: 89.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // Pizza Hut Lajpat Nagar - Slightly lower pricing
    {
      outlet_id: outletIds.pizzahut_ln,
      menu_item_id: menuItemIds.pizzahut_margherita,
      outlet_price: 389.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_ln,
      menu_item_id: menuItemIds.pizzahut_pepperoni,
      outlet_price: 489.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_ln,
      menu_item_id: menuItemIds.pizzahut_veggie,
      outlet_price: 439.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_ln,
      menu_item_id: menuItemIds.pizzahut_garlicbread,
      outlet_price: 189.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // Pizza Hut Dwarka - Limited menu
    {
      outlet_id: outletIds.pizzahut_dwarka,
      menu_item_id: menuItemIds.pizzahut_margherita,
      outlet_price: 379.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_dwarka,
      menu_item_id: menuItemIds.pizzahut_veggie,
      outlet_price: 429.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.pizzahut_dwarka,
      menu_item_id: menuItemIds.pizzahut_garlicbread,
      outlet_price: 179.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // Domino's Karol Bagh - Full menu
    {
      outlet_id: outletIds.dominos_kb,
      menu_item_id: menuItemIds.dominos_margherita,
      outlet_price: 299.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_kb,
      menu_item_id: menuItemIds.dominos_chicken,
      outlet_price: 499.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_kb,
      menu_item_id: menuItemIds.dominos_veg,
      outlet_price: 399.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_kb,
      menu_item_id: menuItemIds.dominos_garlicbread,
      outlet_price: 149.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_kb,
      menu_item_id: menuItemIds.dominos_lemonade,
      outlet_price: 99.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // Domino's Saket - Full menu
    {
      outlet_id: outletIds.dominos_saket,
      menu_item_id: menuItemIds.dominos_margherita,
      outlet_price: 299.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_saket,
      menu_item_id: menuItemIds.dominos_chicken,
      outlet_price: 499.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_saket,
      menu_item_id: menuItemIds.dominos_veg,
      outlet_price: 399.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_saket,
      menu_item_id: menuItemIds.dominos_garlicbread,
      outlet_price: 149.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_saket,
      menu_item_id: menuItemIds.dominos_sprite,
      outlet_price: 85.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },

    // Domino's Gurgaon - Premium pricing
    {
      outlet_id: outletIds.dominos_gurgaon,
      menu_item_id: menuItemIds.dominos_margherita,
      outlet_price: 309.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_gurgaon,
      menu_item_id: menuItemIds.dominos_chicken,
      outlet_price: 519.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_gurgaon,
      menu_item_id: menuItemIds.dominos_veg,
      outlet_price: 419.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      outlet_id: outletIds.dominos_gurgaon,
      menu_item_id: menuItemIds.dominos_lemonade,
      outlet_price: 109.0,
      is_available: true,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ],
};

module.exports = seedData;
